import type { Metadata } from "next";
import "./globals.css";
import { Public_Sans, Open_Sans } from "next/font/google"
import React from "react";

const publicSans = Public_Sans({
  subsets: ["latin"],
  variable: "--font-public-sans",
})

const openSans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-open-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${publicSans.variable} ${openSans.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-body">{children}</body>
    </html>
  );
}
